init

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -22,8 +22,9 @@ jobs:
       - name: Run validation script
         env:
           SFDX_AUTH_URL_MAIN: ${{ secrets.SFDX_AUTH_URL_MAIN }}
+          SFDX_AUTH_URL_UAT: ${{ secrets.SFDX_AUTH_URL_UAT }}
+          SFDX_AUTH_URL_SIT: ${{ secrets.SFDX_AUTH_URL_SIT }}
           REPO_NAME: ${{ github.event.repository.name }}
-          ENVIRONMENT: SFDX_AUTH_URL_MAIN
         run: |
           git config --global --add safe.directory /__w/$REPO_NAME/$REPO_NAME
           lastTag=$(git describe --tags --abbrev=0 --match "${CI_COMMIT_BRANCH}*") || true
@@ -37,31 +38,52 @@ jobs:
           fi
           echo lastCommit $lastCommit
           echo Compare from commitHash $lastCommit
-#          sfdx sgd:source:delta --to $CI_COMMIT_SHA --from $lastCommit --output . --include .include
-#          if ( grep -q '<types>' ./package/package.xml ) || ( grep -q '<types>' ./destructiveChanges/destructiveChanges.xml ) ; then
-#            sfdx_auth_url=SFDX_AUTH_URL_${CI_COMMIT_BRANCH^^}
-#            sfdx_auth_url_value=${!sfdx_auth_url}
-#            if [ -z "$sfdx_auth_url_value" ]; then
-#              echo "---- Missing $sfdx_auth_url from CI/CD variables ----"
-#              exit 1
-#            fi
-#            echo sfdx_auth_url $sfdx_auth_url_value
-#            echo $sfdx_auth_url_value > env.sfdx
-#            sfdx org:login:sfdx-url --sfdx-url-file env.sfdx --set-default
-#            resultId=$(sfdx project:deploy:start \
-#              --manifest package/package.xml \
-#              --post-destructive-changes destructiveChanges/destructiveChanges.xml \
-#              --dry-run \
-#              --ignore-warnings \
-#              --test-level RunLocalTests \
-#              --async \
-#              --json | jq --raw-output '.result.id')
-#            sfdx project:deploy:resume --job-id $resultId
-#            echo $resultId > VALIDATED_DEPLOY_REQUEST_ID.txt
-#            echo "---- Validation Successful ----"
-#          else
-#            echo "---- No changes to deploy ----"
-#          fi
+          sfdx sgd:source:delta --to $CI_COMMIT_SHA --from $lastCommit --output . --include .include
+          
+          branch_name=$(echo "$GITHUB_REF_NAME" | tr '[:lower:]' '[:upper:]')
+            echo "branch_name" $branch_name
+          
+            if [ "$branch_name" == "MAIN" ]; then
+              sfdx_auth_url_value=$SFDX_AUTH_URL_MAIN
+            elif [ "$branch_name" == "UAT" ]; then
+              sfdx_auth_url_value=$SFDX_AUTH_URL_UAT
+            elif [ "$branch_name" == "SIT" ]; then
+              sfdx_auth_url_value=$SFDX_AUTH_URL_SIT
+            else
+              echo "Invalid branch name: $branch_name"
+              exit 1
+            fi
+          
+            echo "sfdx_auth_url_value" $sfdx_auth_url_value
+          
+          if ( grep -q '<types>' ./package/package.xml ) || ( grep -q '<types>' ./destructiveChanges/destructiveChanges.xml ) ; then
+          
+            sfdx_auth_url=SFDX_AUTH_URL_${CI_COMMIT_BRANCH^^}
+            sfdx_auth_url_value=${!sfdx_auth_url}
+          
+          
+          
+            if [ -z "$sfdx_auth_url_value" ]; then
+              echo "---- Missing $sfdx_auth_url from CI/CD variables ----"
+              exit 1
+            fi
+            echo sfdx_auth_url $sfdx_auth_url_value
+            echo $sfdx_auth_url_value > env.sfdx
+            sfdx org:login:sfdx-url --sfdx-url-file env.sfdx --set-default
+            resultId=$(sfdx project:deploy:start \
+              --manifest package/package.xml \
+              --post-destructive-changes destructiveChanges/destructiveChanges.xml \
+              --dry-run \
+              --ignore-warnings \
+              --test-level RunLocalTests \
+              --async \
+              --json | jq --raw-output '.result.id')
+            sfdx project:deploy:resume --job-id $resultId
+            echo $resultId > VALIDATED_DEPLOY_REQUEST_ID.txt
+            echo "---- Validation Successful ----"
+          else
+            echo "---- No changes to deploy ----"
+          fi
         shell: bash
 
       - name: Upload artifact
